# Generated by Django 4.1.1 on 2022-09-26 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('_start', models.DateTimeField()),
                ('_end', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(1, 'Public'), (0, 'Private')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='EventPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prize', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='image/event/prize/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheel_prize.event')),
            ],
        ),
    ]
