# Generated by Django 4.1.1 on 2022-09-26 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wheel_prize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeWinPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_number', models.IntegerField()),
                ('percent', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='eventprize',
            name='image',
            field=models.ImageField(upload_to='media/event/prize/'),
        ),
        migrations.AlterField(
            model_name='eventprize',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='eventprize',
            name='prize',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='PrizeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wheel_prize.event')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wheel_prize.eventprize')),
            ],
        ),
    ]
