# Generated by Django 4.1.1 on 2022-09-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel_prize', '0002_prizewinpercent_alter_eventprize_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizelog',
            name='event',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prizelog',
            name='prize',
            field=models.CharField(max_length=255),
        ),
    ]
