# Generated by Django 4.1.1 on 2022-11-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel_prize', '0003_alter_prizelog_event_alter_prizelog_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(blank=True)),
                ('limit', models.IntegerField(default=0)),
            ],
        ),
    ]
