# Generated by Django 4.1.1 on 2022-11-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel_prize', '0004_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='uid',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
